### ISSUE TITLE
使用Pod进行安装时libwechatsdk.a冲突

### ISSUE THREAD

**Issue by dvlprliu** [magicwindow/mw-iossdk#1]
情况是这样，我的项目里已经存在了libwechatsdk.a文件，同样是用Pod引入，这时引入魔窗SDK的时候报告冲突导致无法安装。   

建议： 可以在两个podspec文件里分别定义一个名为Core的subspec，指向魔窗相关的文件，这样可以使用 `pod 'MagicWindowSDK/Core'`，`pod 'MagicWindowSDKBitcode/Core'` 来解决冲突问题。

**Comment by cafei** [comment]
参考BBS，http://bbs.magicwindow.cn/topic/47
